services:
  - type: web
    name: noise-remover-backend
    runtime: node
    repo: https://github.com/noiseremovercom/noise-reduction-website.git
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    region: singapore
    envVars:
      - key: NODE_ENV
        value: production
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_ORIGINS
        value: https://noise-remover-frontend.onrender.com